### PR TITLE
Add Counter Strike 2 (standard) template

### PR DESCRIPTION
**Pull request by atharva407**
Working template for cs2 dedicated server on linux.

### CODE REVIEW

**Comment by LordRalex** [comment]
https://github.com/pufferpanel/templates/pull/260

**Comment by Lok3rn3t** [comment]
Actually not a bad job, can we make a coop?

**Comment by Lok3rn3t** [comment]
Actually not a bad job for docker, can we make a coop?

**Comment by atharva407** [comment]
sure..

**Pull request closed without merging**
