### PR TITLE
Add ``minecraft-autoplug`` Template

### PR DESCRIPTION
**Pull request by Minionguyjpro**
This adds a template for the AutoPlug client, a client for Minecraft servers with additional features. It runs on top of the Minecraft server, hence the client will execute the Minecraft server Java instance. I've added some notes for things that should be changed to make it work, but when that's all done it will work perfectly.

### CODE REVIEW

**Comment by Minionguyjpro** [comment]
Ohhhh I accidentally edited the purpur files. I will restore them.

**Comment by Minionguyjpro** [comment]
Okay done, I fixed/restored it back as it was. Now all changes shall be correct.

**Comment by LordRalex** [comment]
Can you please order the properties of the files the same?

Please refer to https://github.com/PufferPanel/templates/blob/v2.6/minecraft-vanilla/minecraft-vanilla.json for a desired ordering.

**Comment by Minionguyjpro** [comment]
> Can you please order the properties of the files the same?
> 
> Please refer to https://github.com/PufferPanel/templates/blob/v2.6/minecraft-vanilla/minecraft-vanilla.json for a desired ordering.

The ``build`` and ``version`` flags don't apply to this, as the client does only offer the latest build at a time and it isn't the server software itself, just the client that can run it.

**Comment by LordRalex** [comment]
> > Can you please order the properties of the files the same?
> > Please refer to https://github.com/PufferPanel/templates/blob/v2.6/minecraft-vanilla/minecraft-vanilla.json for a desired ordering.
> 
> The `build` and `version` flags don't apply to this, as the client does only offer the latest build at a time and it isn't the server software itself, just the client that can run it.

Order as in, the data section is first, then the install section, then the run section, and so on. The specific variables are not what I meant.

**Comment by Minionguyjpro** [comment]
Oh sorry, I didn't understand it correctly. I'll look into it this
afternoon. Shall I do the same for the Docker version of the template?

Op do 19 okt. 2023 19:47 schreef Joshua Taylor ***@***.***>:

**Comment by Minionguyjpro** [comment]
> > > Can you please order the properties of the files the same?
> > > Please refer to https://github.com/PufferPanel/templates/blob/v2.6/minecraft-vanilla/minecraft-vanilla.json for a desired ordering.
> > 
> > The `build` and `version` flags don't apply to this, as the client does only offer the latest build at a time and it isn't the server software itself, just the client that can run it.
> 
> Order as in, the data section is first, then the install section, then the run section, and so on. The specific variables are not what I meant.

Although, why does Purpur use this ordering instead?

**Comment by Minionguyjpro** [comment]
@LordRalex Done! I fixed the ordering and it should be correct now.

**Comment by Minionguyjpro** [comment]
@LordRalex I hope you'll be able to merge this soon.

**Pull request merged**
