### PR TITLE
Add FiveM template

### PR DESCRIPTION
**Pull request by gameserversmanagement**

### CODE REVIEW

**Comment by gOOvER** [comment]
i wopuld be careful with adding FiveM. FiveM Team ban Gameserver Manager, when guys sell Gameserver with it

**Comment by LexFuturorum** [comment]
Pufferpanel isn't meant to be a commercial platform, that shouldn't be a problem

**Review by gibbiemonster — CHANGES_REQUESTED** [review]
Looks fine, just capitalize 'Please'

**Comment by MusicDiscord** [comment]
Hi, i'm trying to make a fivem server through pufferpanel but whenever i try to start it i get th is message.

 Starting process: /usr/bin/bash start_no_edit.sh +exec server.cfg../run.sh: line 8: /var/lib/pufferpanel/servers/bf35a195/alpine/opt/cfx-server/ld-musl-x86_64.so.1: cannot execute binary file: Exec format error
../run.sh: line 8: /var/lib/pufferpanel/servers/bf35a195/alpine/opt/cfx-server/ld-musl-x86_64.so.1: Success

I was was wondering if someone can help me out?

**Comment by gOOvER** [comment]
> Hi, i'm trying to make a fivem server through pufferpanel but whenever i try to start it i get th is message.
> 
> Starting process: /usr/bin/bash start_no_edit.sh +exec server.cfg../run.sh: line 8: /var/lib/pufferpanel/servers/bf35a195/alpine/opt/cfx-server/ld-musl-x86_64.so.1: cannot execute binary file: Exec format error ../run.sh: line 8: /var/lib/pufferpanel/servers/bf35a195/alpine/opt/cfx-server/ld-musl-x86_64.so.1: Success
> 
> I was was wondering if someone can help me out?

sounds like you use ARM64.

FiveM is not compatible with ARM64

**Comment by MusicDiscord** [comment]
So there isn't a way to get arround it?

**Comment by LexFuturorum** [comment]
nope.

**Pull request merged**
