### PR TITLE
Add the terraria-1.4-tmodloader template

### PR DESCRIPTION
**Pull request by Amatsu-Kami**
Rebase the template made by rakles to v2.6 to follow the formatting rules.

### CODE REVIEW

**Comment by LordRalex** [comment]
How does this differ from https://github.com/PufferPanel/templates/blob/v2.6/terraria-tmodloader/terraria-tmodloader.json ?

**Comment by Amatsu-Kami** [comment]
The existing template doesn't work for tmodloader 1.4 while this one works only for tmodloader 1.4

**Comment by Amatsu-Kami** [comment]
@LordRalex why was this closed ?

**Comment by LordRalex** [comment]
At this stage, the original template should be updated, since that is the way tmodloader is moving. A version-specific one should only exist for older versions.

**Pull request closed without merging**
