### PR TITLE
Satisfactory Deticated Servers

### PR DESCRIPTION
**Pull request by MrNavaStar**
#### A template for installing and running the new official satisfactory servers
- More info at the [Wiki](https://satisfactory.fandom.com/wiki/Dedicated_servers#Initial_configuration)

### CODE REVIEW

**Comment by RevLaw** [comment]
Sadly it will not work in the PufferPanel Docker environment. The command './FactoryServer.sh' is failing because it will be run as the container 'root' user. Hope Someone will fix the Docker part. 🙏

**Comment by gOOvER** [comment]
use the Startup CMD from the .sh as startcmd. No need to chmod x it in every start 

```
./Engine/Binaries/Linux/UE4Server-Linux-Shipping FactoryGame ?listen -Port=7777 -ServerQueryPort=15777 -BeaconPort=15000
```

**Comment by MrNavaStar** [comment]
We still need the chmod +x on the first run though - Do you think I should I do that in the install command instead?

**Comment by Laurennus** [comment]
> We still need the chmod +x on the first run though - Do you think I should I do that in the install command instead?

Yes.

Also a new problem has emerged in the Linux version! Server fails to bind port (and to run) without setting `-multihome=0.0.0.0` as a launch parametre due to some new IPv6 stuff. Could also add as a variable defaulting to 0.0.0.0 in case someone needs to modify it.

**Comment by MrNavaStar** [comment]
Oh your right, I will add support for the new features later today

**Comment by MrNavaStar** [comment]
Stopping the server now works and I fixed the other things you guys mentioned

**Comment by ghost** [comment]
Is anyone else still having issues with starting the server? I get:

DAEMON  Starting container
Refusing to run with the root privileges.
DAEMON  Running post-execution steps

**Comment by breitLight** [comment]
> Is anyone else still having issues with starting the server? I get:
> 
> DAEMON Starting container Refusing to run with the root privileges. DAEMON Running post-execution steps

I am running into the same issue.

**Pull request merged**
